"""New migration

Revision ID: 965f6fd09496
Revises: 
Create Date: 2022-01-12 18:38:06.751919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965f6fd09496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dbn', sa.String(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('total_enrolments', sa.Integer(), nullable=True),
    sa.Column('grade_k', sa.Integer(), nullable=True),
    sa.Column('grade_1', sa.Integer(), nullable=True),
    sa.Column('grade_2', sa.Integer(), nullable=True),
    sa.Column('grade_3', sa.Integer(), nullable=True),
    sa.Column('grade_4', sa.Integer(), nullable=True),
    sa.Column('grade_5', sa.Integer(), nullable=True),
    sa.Column('grade_6', sa.Integer(), nullable=True),
    sa.Column('grade_7', sa.Integer(), nullable=True),
    sa.Column('grade_8', sa.Integer(), nullable=True),
    sa.Column('female', sa.Integer(), nullable=True),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('asian', sa.Integer(), nullable=True),
    sa.Column('black', sa.Integer(), nullable=True),
    sa.Column('hispanic', sa.Integer(), nullable=True),
    sa.Column('white', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.Column('ell_spanish', sa.Integer(), nullable=True),
    sa.Column('ell_chinese', sa.Integer(), nullable=True),
    sa.Column('ell_bengali', sa.Integer(), nullable=True),
    sa.Column('ell_arabic', sa.Integer(), nullable=True),
    sa.Column('ell_haitian_creole', sa.Integer(), nullable=True),
    sa.Column('ell_french', sa.Integer(), nullable=True),
    sa.Column('ell_russian', sa.Integer(), nullable=True),
    sa.Column('ell_korean', sa.Integer(), nullable=True),
    sa.Column('ell_urdu', sa.Integer(), nullable=True),
    sa.Column('ell_other', sa.Integer(), nullable=True),
    sa.Column('ela_takers', sa.Integer(), nullable=True),
    sa.Column('ela_level_1', sa.Integer(), nullable=True),
    sa.Column('ela_level_2', sa.Integer(), nullable=True),
    sa.Column('ela_level_3', sa.Integer(), nullable=True),
    sa.Column('ela_level_4', sa.Integer(), nullable=True),
    sa.Column('math_takers', sa.Integer(), nullable=True),
    sa.Column('math_level_1', sa.Integer(), nullable=True),
    sa.Column('math_level_2', sa.Integer(), nullable=True),
    sa.Column('math_level_3', sa.Integer(), nullable=True),
    sa.Column('math_level_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
